name: projeto_livre_pam
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bcrypt: ^1.1.3
  country_flags: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  logging: ^1.3.0
  mocktail: ^1.0.4
  multiple_result: ^5.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6
  test: ^1.26.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/tourist_api/destinations.json
    - assets/tourist_api/images/
    - assets/brand/logo_light.svg
    - assets/sql/create_db.sql
